### ISSUE TITLE
Refactor all the CSS

### ISSUE THREAD

**Issue by hirooutdoor** [hirooutdoor/instalikeapp#11]

**Comment by hirooutdoor** [comment]
- [x] profileの画像の周りのborderに中央よせが効かない！

```scss
.profile_img_border {
    // display:inline-block;
    // justify-content: center;
    // align-items: center;
    // border: 1px solid #E91E63;
    // border-radius: 50%;
    // max-width: 84px;
    // height: 84px;
    // box-sizing: border-box;
    // text-align:center;
        margin-top: 32px;
        //中央よせが効かない問題
    img {
        width: 76.88px;
        height: 76.88px;
        border-radius: 50%;
        margin:0 auto;
        display:block;
    }
}
```
